/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source E0:99:71:6A:23:96 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 5c:70:a3:4b:00:92 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source F4:42:8F:49:D8:F9 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source C8:A8:23:EA:82:D8 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 7C:61:93:98:97:0F -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f8:a9:d0:4a:1e:00 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f0:5b:7b:4d:93:ab -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:76:b7:65:c9:35 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 88:07:4b:cc:ba:62 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source a4:84:31:f5:42:b8 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source b8:86:87:06:7a:15 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source BC:44:86:AB:E6:9B -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 90:3c:92:56:9f:f3 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 78:d7:5f:8b:95:6c -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c8:ff:28:6b:5b:1b -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c8:ff:28:6b:5b:1b -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source ac:5a:14:15:90:98 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 38:0B:40:F5:61:6A -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 84:2E:27:8D:81:CF -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source bc:54:36:4f:92:94 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c4:43:8f:b3:c2:bb -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source E0:99:71:6A:59:08 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source F8:84:F2:B7:4B:EF -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 6c:8d:c1:a9:d7:7a -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 38:2d:d1:4f:c4:4f -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 64:bc:0c:2e:0f:82 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f4:42:8f:64:22:41 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source AC:5A:14:04:EA:3E -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source d0:53:49:c4:61:51 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:76:b7:33:a0:11 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 8c:1a:bf:c5:4c:fe -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c8:14:79:f3:00:a8 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 10:41:7f:55:31:2c -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:08:c2:00:0e:c0 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source B8:5A:73:1E:36:F7 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 48:3b:38:80:ba:c5 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source d0:25:98:6e:a5:64 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source a8:8e:24:10:45:09 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 18:83:31:a9:0e:27 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 00:34:da:8d:69:41 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source A4:EB:D3:F0:E4:DB -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 20:55:31:a1:7b:53 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 18:83:31:9d:f3:71 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f0:db:e2:3f:84:78 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:3D:88:0F:BA:D0 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 0c:48:85:dc:89:48 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 90:00:DB:BE:9A:ED -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source B8:5A:73:12:EF:D1 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 78:3a:84:9c:04:bd -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source AC:EE:9E:CA:23:13 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f4:42:8f:49:83:13 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f0:5b:7b:5d:c1:6f -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 44:00:10:2b:f6:a6 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:76:b7:65:9b:ff -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 8c:3a:e3:4c:71:ab -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 90:00:DB:AB:04:71 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 00:F4:6F:9C:5E:F1 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:ee:8b:37:6e:2f -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source a8:7c:01:fb:7b:d8 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 38:0B:40:F9:7D:52 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source e0:b5:2d:6a:7a:30 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 80:4e:81:1d:13:51 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 88:07:4b:b2:25:32 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 04:db:56:45:a2:7b -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source e8:3a:12:16:bb:49 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 00:cd:fe:72:16:28 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 78:d7:5f:7e:90:c0 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source a0:b4:a5:92:34:d7 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 30:10:b3:5b:e4:32 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 88:c9:d0:c5:82:79 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:ee:8b:4b:e0:51 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 3C:A1:0D:07:E4:1F -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 18:22:7e:b1:df:12 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 28:cc:01:5b:62:fd -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source e4:fa:ed:1e:2f:f5 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source cc:f3:a5:98:4a:51 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 9c:35:eb:49:b0:dd -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c4:9a:02:10:50:a2 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:76:b7:27:f8:e7 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 40:30:04:4C:F4:9C -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source AC:EE:9E:A8:DB:80 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 00:34:da:92:27:a6 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source ac:ee:9e:a8:3b:14 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 10:92:66:06:f9:c9 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 84:2e:27:72:0f:19 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source AC:EE:9E:E5:6B:FD -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 18:22:7e:ad:37:5a -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 14:32:D1:9D:60:A3 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c4:43:8f:65:d7:1c -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:D4:2B:23:B3:2E -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 84:2E:27:6A:C2:FB -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source E0:99:71:50:4D:04 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 80:4e:81:08:d2:55 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source bc:6c:21:70:ea:6c -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source dc:ee:06:e6:23:61 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source a0:91:69:ee:24:ff -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 24:4B:81:9F:A5:C0 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c4:9a:02:2c:a6:93 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source a4:84:31:e9:7c:f2 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 84:2e:27:b2:6e:91 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 50:A4:C8:9F:55:33 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:a1:a2:b9:2f:26 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 50:A4:C8:9E:5C:F7 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source E0:99:71:50:27:E2 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 78:d7:5f:96:55:69 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source F4:42:8F:35:43:CD -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:76:b7:98:02:37 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 34:4D:F7:0B:40:63 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source C0:65:99:EC:61:11 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 5C:96:9D:A5:FC:E5 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:76:b7:cf:9d:9d -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 18:83:31:9e:4e:61 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 84:2e:27:86:f4:97 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source ac:ee:9e:ff:2e:e3 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 24:4b:81:97:b4:0e -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:ee:8b:3a:24:4d -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f4:5c:89:b2:ad:01 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f4:42:8f:2d:b6:1f -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 00:f4:6f:96:6b:57 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f0:db:e2:cf:f8:48 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 20:55:31:ad:3f:49 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source d8:31:cf:30:50:56 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 90:00:db:be:e6:d7 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source A8:7C:01:E5:2B:6C -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source cc:25:ef:38:17:01 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:EE:8B:17:5E:FF -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:76:b7:de:ee:9b -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source E8:92:A4:ED:B2:FA -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:EE:8B:08:21:CF -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source d0:59:e4:f3:54:20 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source A0:B4:A5:7C:75:62 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 14:89:fd:f6:ed:7b -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 80:4e:81:15:2a:b3 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 60:a3:7d:7d:52:41 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 10:2a:b3:7c:e1:0e -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:76:b7:26:5e:3b -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source e4:fa:ed:03:72:b0 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source E8:3A:12:0C:C4:0D -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 38:0B:40:FB:E3:58 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source e4:fa:ed:0e:09:97 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source e8:3a:12:09:77:97 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 38:ca:da:6c:23:34 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source E0:CB:EE:EB:C0:56 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 40:b0:fa:c9:bf:2c -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 30:52:cb:20:34:41 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source a8:7c:01:fc:86:fa -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:76:b7:9d:6e:b7 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 30:f7:72:31:7c:c7 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 20:55:31:78:EF:BD -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 58:7f:57:4c:5e:91 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c4:9a:02:68:d6:c3 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 8C:3A:E3:95:48:54 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source a0:39:f7:7d:0f:95 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source B8:5A:73:03:DE:FB -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source e0:99:71:68:4d:a8 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 18:83:31:B1:AA:BB -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source E0:CB:EE:E2:9D:5F -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source BC:72:B1:C9:5F:7D -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source F8:A9:D0:48:DB:79 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source D0:57:85:FA:E0:6E -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 3c:a1:0d:13:fa:af -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source cc:f3:a5:97:06:ed -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f4:42:8f:54:e6:f9 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:EE:8B:16:60:33 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 8c:1a:bf:65:c8:46 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source f8:a9:d0:50:cf:57 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 38:2D:D1:4D:1C:CD -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 00:f4:6f:99:3f:57 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source bc:54:36:0f:17:d9 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 24:DB:ED:F0:A3:DC -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c8:14:79:e7:e4:49 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 84:2E:27:93:06:95 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 94:d7:71:ea:a9:53 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 80:4e:81:08:ec:03 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source cc:f3:a5:97:f7:5d -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 60:e3:ac:e8:ec:73 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 4C:A5:6D:95:67:99 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source b8:5a:73:0b:3c:11 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 98:e0:d9:1c:43:c9 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 2c:54:cf:e5:a2:27 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 8c:1a:bf:49:90:e4 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c8:38:70:60:17:2f -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 90:fd:61:70:df:56 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 80:4e:81:32:60:bb -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 60:36:dd:1e:f7:8f -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source ac:ee:9e:cd:b7:7d -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source d0:59:e4:d3:16:a6 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source a4:5e:60:64:2a:2f -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:EE:8B:2F:BF:79 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source AC:36:13:58:34:2B -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source F4:42:8F:37:51:EF -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source C0:11:73:FD:49:B5 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 0c:51:01:25:e0:c5 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source CC:FA:00:AC:6D:CE -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 88:07:4b:b7:0a:84 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 48:59:29:ee:4d:12 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c4:43:8f:ab:1a:29 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source c0:11:73:f5:f9:99 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 5c:70:a3:7e:83:ee -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 2c:54:cf:fc:22:64 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 08:3d:88:0e:54:4a -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source E0:CB:EE:E6:AE:BF -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source ac:7b:a1:bf:10:ee -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source E8:92:A4:F0:40:98 -j ACCEPT 
/sbin/iptables -t nat -A PREROUTING -i eth1 -m mac --mac-source 1C:AF:05:A4:A5:41 -j ACCEPT 
